[variables]
NIXPACKS_JDK_VERSION = "11"

[phases.build]
cmds = [
  "mvn clean package -DskipTests",
  "ls -la target/",
  "find target -name '*.jar' -type f"
]

[phases.start]
cmd = "java -jar target/*.jar --server.port=$PORT" 